services:
  - type: static
    name: marketing-blog-frontend
    env: static
    buildCommand: npm run build
    publishPath: dist/frontend/browser
    routes:
      # Support Angular routing and deep links
      - type: rewrite
        source: /*
        destination: /index.html
